# Generated by Django 3.0.1 on 2019-12-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=6, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
    ]
