# Generated by Django 3.0.1 on 2019-12-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clogin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keys',
            name='score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='keys',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
