# Generated by Django 3.0.1 on 2019-12-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clogin', '0002_auto_20191230_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keys',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
